spring:
    profiles:
        active:
        - dev
        
---

spring:
    applciation:
        name: microservicecloud-config-dev
    profiles: dev
    
    
--- 


spring:
    applciation:
        name: microservicecloud-config-test
    profiles: test