spring:
 profiles:
  active:
  - dev
        
---


server:
 port: 8201
spring:
 applciation:
  name: microservicecloud-config-client
 profiles: dev

eureka:
 client:
  service-url: 
   defaultZone: http://eureka7001.com:7001/eureka/
    
    
--- 

server:
 port: 8202
spring:
 applciation:
  name: microservicecloud-config-client
 profiles: test
 
eureka:
 client:
  service-url: 
   defaultZone: http://eureka7001.com:7001/eureka/